### ISSUE TITLE
Use styling pattern consistently

### ISSUE THREAD

**Issue by leusgalvan** [leusgalvan/fixture#25]
Pick either useStyles or withStyles pattern and stick to it in all components.

**Comment by Simonpedro** [comment]
Maybe we could use the following convention:

- When a component style is not expected to be changed from the outside, let's use useStyles (this would be true for most of the components, not to say for all).
- When a component style may be changed from the outside, let's use makeStyles.

What u think?

**Comment by leusgalvan** [comment]
What do you mean by changing style from outside?

**Comment by Simonpedro** [comment]
As stated [here](https://material-ui.com/customization/components/#overriding-styles-with-classes), when you style a component using `makeStyles` you'll be able to pass your own classes through the prop `classes`, to style the inner parts of a component.

In the example, the component our component would be Button (looked from outside, from its usage)
